### ISSUE TITLE
Some problems in this spectacular plugin

### ISSUE THREAD

**Issue by haralake** [jan-vince/smallrecords#10]
First of all i want to say that this is one of the best plugins out there. Now i want to point some issues:
1. After you create a record list on backend, you open the first record and down left side on the navigation arrows if i click the left arrow i get:
`Missing argument 2 for JanVince\SmallRecords\Controllers\Records::update()`

2. I try to create a record list page and a record details page but something is wrong with the slug. I try to figure out what is the problem without success. First i create record details page with name record, i throw inside component record and i give the url /record/:slug. Then i create record list page with name records, i throw inside component records, i select record details page inside component. I get the records on frontend but when i click on one record i don't get the detailed page of record. Slugs are wrong. What i missing here?

3. I search for a pagination but i didn't found one. I guess this is something i must do by my self. However is a very good option to implement. 

4. Inside database i saw that on every record on records table is a category_id table that stores category table id's. But there is also a pivot table for categories and records. I really confused here. 2 ways for storing category id s on records?

I'm really sorry for any mistakes, and for your time.

Thank you

**Comment by jan-vince** [comment]
Hi @haralake and many thanks. 

ad 1) You mean arrows in **right** bottom ?

This problem is already issued but I cannot replicate it :(

If you can send me dump of your records from DB I can try to find a problem


ad 2) As I do not use component's default code to render records I have never noticed this.

I will fix this in next release (will post today). There will be new component's property (Detail page param), where you can add your own param ('slug' or 'record') and record's URL will be added.


ad 3) No - sorry. 

But I will note this and add pagination as soon as I need it myself :)


ad 4) You can assign one main category and also many secondary categories.

I do use this for small eShops where I want a product to appear in several categories (like Sale, ...) but still belongs to a one main category.


Best regards,

Jan

**Comment by haralake** [comment]
Thank you for quick response! I will try the updated version.
