### ISSUE TITLE
Unable get the data of individual record 

### ISSUE THREAD

**Issue by kgangadhar** [jan-vince/smallrecords#54]
i have a page with list of services(treatment.htm) when i click on each service it needs to goto its respective page...

in treatment.htm added record component and link as treatment.htm , in treatments page record detail component added but still  data not visible in the detail page.. tried all the ways but i'm unable to where was the mistake 
![errors](https://user-images.githubusercontent.com/6524303/61208602-6a3c4f80-a715-11e9-8d34-595d4955555f.jpg)

**Comment by jan-vince** [comment]
Hi @kgangadhar 

I would say the problem is in link on `/treatment` page.

What URL you get on /treatments page?

I would go with `{{ 'tratments-page|page({'slug':service.slug}) }}

Look in documentation - there is a complete guide (or in the plugin directory in `/components/records/default.htm` file).


Sorry for late answer.
